### ISSUE TITLE
Test suite is failing on RISC architectures

### ISSUE THREAD

**Issue by superm1** [hughsie/libxmlb#10]
Since libxmlb was recently uploaded to Debian it gets tested on a variety of weird ports.

sparc64, riscv64, hppa and hurd-i386 are all failing.

sparc64 and risv64 are failing like this:
```
query[last]: 33.236ms
query[all]: 21.513ms
query[x5000]: 6421.991ms
query[x5000]: 7262.447ms
(/<<PKGBUILDDIR>>/obj-riscv64-linux-gnu/src/xb-self-test:19570): XbSilo-DEBUG: 03:12:44.900: ignoring index: no results for XPath query 'components/component/id[text()='dave']'
(/<<PKGBUILDDIR>>/obj-riscv64-linux-gnu/src/xb-self-test:19570): XbSilo-DEBUG: 03:12:44.901: ignoring index: failed to process components/component/DAVE: element name DAVE is unknown in silo
create index: 81.751ms
-------

Full log written to /<<PKGBUILDDIR>>/obj-riscv64-linux-gnu/meson-logs/testlog.txt
FAILED: meson-test 
/usr/bin/meson test --no-rebuild --print-errorlogs
ninja: build stopped: subcommand failed.
dh_auto_test: cd obj-riscv64-linux-gnu && LC_ALL=C.UTF-8 MESON_TESTTHREADS=1 ninja test returned exit code 1
make: *** [debian/rules:4: build-arch] Error 1
```
Full log riscv64: https://buildd.debian.org/status/fetch.php?pkg=libxmlb&arch=riscv64&ver=0.1.6-1&stamp=1549509209&raw=0
Full log sparc64: https://buildd.debian.org/status/fetch.php?pkg=libxmlb&arch=sparc64&ver=0.1.6-1&stamp=1549495495&raw=0

hurd-i386 fails like this:
```
(/<<PKGBUILDDIR>>/obj-i686-gnu/src/xb-self-test:4512): XbSilo-DEBUG: 22:50:43.845: 0.00ms      save file
(/<<PKGBUILDDIR>>/obj-i686-gnu/src/xb-self-test:4512): XbSilo-DEBUG: 22:50:43.845: 0.00ms      parse blob
(/<<PKGBUILDDIR>>/obj-i686-gnu/src/xb-self-test:4512): XbSilo-DEBUG: 22:50:43.845: 0.00ms      loaded file
--- stderr ---
**
ERROR:../src/xb-self-test.c:546:xb_builder_ensure_func: 'xb_silo_is_valid (silo)' should be FALSE
-------

Full log written to /<<PKGBUILDDIR>>/obj-i686-gnu/meson-logs/testlog.txt
FAILED: meson-test 
/usr/bin/meson test --no-rebuild --print-errorlogs
ninja: build stopped: subcommand failed.
dh_auto_test: cd obj-i686-gnu && LC_ALL=C.UTF-8 MESON_TESTTHREADS=1 ninja test returned exit code 1
debian/rules:4: recipe for target 'build-arch' failed
make: *** [build-arch] Error 1
```
Full log: https://buildd.debian.org/status/fetch.php?pkg=libxmlb&arch=hurd-i386&ver=0.1.6-1&stamp=1549493454&raw=0

hppa failed by the build process dying (might not be relevant)
```
/libxmlb/speed: (/<<PKGBUILDDIR>>/obj-hppa-linux-gnu/src/xb-self-test:23444): XbSilo-DEBUG: 04:31:36.218: compiling a83a3acf09667acb3caa53256b43e8cf308c4d1c?
import+save: 7747.216ms
mmap load: 0.820ms
query[first]: 0.194ms
query[last]: 34.237ms
query[all]: 35.710ms
query[x5000]: 5974.778ms
-------

Full log written to /<<PKGBUILDDIR>>/obj-hppa-linux-gnu/meson-logs/testlog.txt
FAILED: meson-test 
/usr/bin/meson test --no-rebuild --print-errorlogs
ninja: build stopped: subcommand failed.
dh_auto_test: cd obj-hppa-linux-gnu && LC_ALL=C.UTF-8 MESON_TESTTHREADS=1 ninja test returned exit code 1
make: *** [debian/rules:4: build-arch] Error 1
```
Full log: https://buildd.debian.org/status/fetch.php?pkg=libxmlb&arch=hppa&ver=0.1.6-1&stamp=1549513937&raw=0

**Comment by hughsie** [comment]
> ERROR:../src/xb-self-test.c:546:xb_builder_ensure_func: 'xb_silo_is_valid (silo)' should be FALSE

This is because the inotify watch on the /tmp/temp.xmlb file isn't being triggered within 2 seconds. If you can change the `xb_test_loop_run_with_timeout()` 2000ms timeout to something like 10s and re-run the build I'd be interested to see if it's just super slow.

> 2/2 xb-self-test                            TIMEOUT 30.28 s 

It looks like the tests might be taking more than 30 seconds to run on some architectures. Can you try disabling the `xb_speed_func()` and `xb_threading_func()` tests, and if that works I'll hide them behind a not-by-default test switch. Thanks.

**Comment by superm1** [comment]
I don't have easy access to just poke those builders, need to drop a patch in place and try to re-run them.  Can you plumb it how you want it and I'll get the patch put in place to give it another test run.

> It looks like the tests might be taking more than 30 seconds to run on some architectures. Can you try disabling the `xb_speed_func()` and `xb_threading_func()` tests, and if that works I'll hide them behind a not-by-default test switch. Thanks.

Yeah in general I think any speed derived tests end up being a not so great idea since you don't know how much of a share of the CPU load a given build job gets to have on a large shared buildd.

**Comment by superm1** [comment]
It looks like these two fixes worked.
