### ISSUE TITLE
Please install xb-tool into bin instead of libexec

### ISSUE THREAD

**Issue by vagrantc** [hughsie/libxmlb#123]
I am curious why xb-tool is installed to libexec instead of bin, as README.md suggests it should be callable by the user and thus available in PATH, but typically libexec is not included in PATH, and arguably it shouldn't be. from https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s07.html:

> /usr/libexec includes internal binaries that are not intended to be executed directly by users or shell scripts.

Thanks!

**Comment by hughsie** [comment]
Ya, I guess that makes sense. We'd also need a manpage too, although that can be a skeleton that directs to --help.
