### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [hughsie/libxmlb#126]
I would like to point out that identifiers like “[`__LIBXMLB_H_INSIDE__`](https://github.com/hughsie/libxmlb/blob/567d261706add40cbe6a5acbd2a3f504b80449de/src/xmlb.h#L9 "Update candidate")” and “[`_XbBuilderClass`](https://github.com/hughsie/libxmlb/blob/567d261706add40cbe6a5acbd2a3f504b80449de/src/xb-builder.h#L22 "Another update candidate")” [do eventually not fit](https://wiki.sei.cmu.edu/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
💭 Would you like to adjust your selection for unique names?

**Comment by hughsie** [comment]
I think this is an exceptionally common style used by thousands of projects. I don't think it's useful to change them (or in the second case, even _possible_) at this point, sorry.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://en.cppreference.com/w/cpp/language/identifiers#In_declarations "Description for C++ identifiers")? :thinking:

**Comment by hughsie** [comment]
The double underscore isn't reserved in C, only C++.

**Comment by elfring** [comment]
👀 Please take another look at the involved language specifcations.

💭 I hope that the probability can be considerably reduced for undesirable programming mistakes.

**Comment by hughsie** [comment]
I did take another look. Where does it say that you can't have double underscores in the C (not CPP) specification?

**Comment by elfring** [comment]
Do you find the wording “All identifiers that begin with an underscore and either an uppercase letter or another underscore are always reserved for any use.” in a section like 7.1.3 from the official version of the standard for the programming language “C”?

**Comment by elfring** [comment]
The use of reserved identifiers is valid for implementations of the programming languages “C” and “C++”.

Ignorance of corresponding rules triggers risks for undesirable software behaviour, doesn't it? 🤔

**Comment by hughsie** [comment]
You fell for my trick. You're a good bot, but not that good. Comment again and I'll report you.

**Comment by elfring** [comment]
I find it strange that you interpret the provided constructive advice as coming from a “bot”.
Please take another look at available information sources.

**Comment by ximion** [comment]
@hughsie is right though - also, this style is so insanely common that you would be crazy to break it on purpose as language author. Avoiding it doesn't even help you to not get bitten by words becoming reserved words in future (like the use of "requires", which is a keyword in C++ now, `auto` was a similar case but had a very long phase where it was known to be coming)
So, in general, changing any of this is a lot of work for pretty much zero gain.

**Comment by hughsie** [comment]
@ximion it's a bot, don't poke the bear 🙂
