### ISSUE TITLE
Converters don't nest - can't handle .yml.gz

### ISSUE THREAD

**Issue by robert-ancell** [hughsie/libxmlb#13]
libxmlb assumes the result of a gzipped file is XML, instead of checking the MIME type of the decompressed data. This means that .yml.gz files can't be handled by the converter.

**Comment by hughsie** [comment]
Got a patch handy? I'm just on PTO. Thanks.

**Comment by robert-ancell** [comment]
I will attempt to write one but haven't started yet. I figure the best thing is to re-check the mime type after a gzip decode.

**Comment by robert-ancell** [comment]
https://github.com/hughsie/libxmlb/pull/14

**Comment by hughsie** [comment]
Okay, I've had a go at this too; I took what you did and rewrote it -- there is a proper context object we can extend in the future if we need to now. I've also pushed a wip/hughsie/XbBuilderSource-adapter branch in gnome-software which uses this new API -- feedback very welcome.
