### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by superm1** [hughsie/libxmlb#16]
Would you mind tagging a new release?  I'd like to get 04e88acc82a53367b154d5f371 into Debian/Ubuntu to unblock https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/1817223 but rather not just cherry-pick the the fix if possible.

**Comment by ximion** [comment]
Keep in mind that the Debian freeze is on the 12.03. and with the current 10day migration period, any upload done now will not make it into the next Debian release.
So, if you need this in, check with the release team first to get a freeze exception (this bug would certainly at the current freeze status allow for an exception).

**Comment by hughsie** [comment]
This also needs a change and release of appstream-glib, IIUC. I can work on that tomorrow.

**Comment by hughsie** [comment]
Done!
