### ISSUE TITLE
SEGV in xb_silo_query_node_matches by calling xb_silo_query

### ISSUE THREAD

**Issue by spencerwuwu** [hughsie/libxmlb#208]
Hi libxmlb devs,

I was trying to fuzz libxmlb with the harness attached, and triggered a SEGV when calling `xb_silo_query`.   
The error log is shown as below. Could this be a bug in the library?
```
==2992767==ERROR: AddressSanitizer: SEGV on unknown address 0x7f4487cebf03 (pc 0x556c65dbdddb bp 0x7fff5008c690 sp 0x7fff5008c520 T0)
==2992767==The signal is caused by a READ memory access.
    #0 0x556c65dbdddb in xb_silo_query_node_matches /src/libxmlb/_builddir/../src/xb-silo-query.c:36:34
    #1 0x556c65dbdddb in xb_silo_query_section_root /src/libxmlb/_builddir/../src/xb-silo-query.c:205:8
    #2 0x556c65dbbe88 in xb_silo_query_part /src/libxmlb/_builddir/../src/xb-silo-query.c:271:9
    #3 0x556c65dbbe88 in silo_query_with_root /src/libxmlb/_builddir/../src/xb-silo-query.c:349:8
    #4 0x556c65db002b in LLVMFuzzerTestOneInput /src/new_fuzzers/libxmlb__xb_silo_query__0.c:65:1
    #5 0x556c65c64990 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:614:13
    #6 0x556c65c4fc05 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:327:6
    #7 0x556c65c5569f in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:862:9
    #8 0x556c65c80942 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #9 0x7f444dd13d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #10 0x7f444dd13e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #11 0x556c65c47ded in _start (/users/weicheng/auto_extract/exp/oss-fuzz_libfuzzer/build/out/libxmlb/libxmlb__xb_silo_query__0+0x378ded)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /src/libxmlb/_builddir/../src/xb-silo-query.c:36:34 in xb_silo_query_node_matches
==2992767==ABORTING
```
Attaching the fuzzing harness, statically compiled executable, and the crashing input.   
The harness takes an input and split it into half. The first half is dumped to an temporary xmlb file. Then load and query the file with the second half of the input.

https://drive.google.com/drive/folders/1Hl-Pr_NCLRPutLRDUtdgHRvytZti9eRg?usp=drive_link

Please feel free to let me know if you need any additional information.

Best,
Spencer

**Comment by hughsie** [comment]
Can you give me the AFL/hongfuzz cli you're using too please.

**Comment by spencerwuwu** [comment]
Hi Richard,

Thank you for the fast response and the information!

I was fuzzing it with oss-fuzz as part of my gradschool research. Please find my clone with the build of libxmlb in this repo.   
[https://github.com/spencerwuwu/libxmlb_oss-fuzz](https://github.com/spencerwuwu/libxmlb_oss-fuzz)   
The scripts & harnesses to compile libxmlb is in `projects/libxmlb`. Run the following command at the root of this repo to compile. Docker is required.
```
infra/helper.py build_fuzzers libxmlb
```
Using libfuzzer as the default fuzzer with address sanitizer.

Once succeed, the executable files can be found in `build/out/libxmlb`. 
If you're on a x86 linux system, the files should be directly executable. Running them without arguments will start fuzzing directly. Running with passing a file path as an argument will just execute with the file as input (can also debug with gdb here).

If you're interested in it, we can probably also submit these building scripts to upstream oss-fuzz later, with fuzzing harrnesses that's reasonable to you.

**Comment by hughsie** [comment]
> I was fuzzing it with oss-fuzz as part of my gradschool research

That sounds like a good project!

> Please find my clone with the build of libxmlb in this repo

I think it probably makes sense to sip the harness in the upstream project -- e.g. this is what I do in fwupd: https://github.com/fwupd/fwupd/blob/main/libfwupdplugin/fu-fuzzer-main.c and https://github.com/fwupd/fwupd/blob/main/libfwupdplugin/fu-fuzzer-firmware.c.in

> we can probably also submit these building scripts to upstream oss-fuzz later

Yes, but I think we need to fix the worst problems first :) e.g. you probably want to submit something like this as a pull request for a really good grade :)

	diff --git a/src/xb-silo.c b/src/xb-silo.c
	index 80a66bb..1fa5d2b 100644
	--- a/src/xb-silo.c
	+++ b/src/xb-silo.c
	@@ -219,6 +219,10 @@ XbSiloNode *
	 xb_silo_get_node(XbSilo *self, guint32 off)
	 {
		XbSiloPrivate *priv = GET_PRIVATE(self);
	+       if (G_UNLIKELY(off >= priv->strtab)) {
	+               g_critical("offset %u is outside the expected range", off);
	+               return NULL;
	+       }
		return (XbSiloNode *)(priv->data + off);
	 }
