### ISSUE TITLE
Support the XPath `and` operator

### ISSUE THREAD

**Issue by pwithnall** [hughsie/libxmlb#29]
In an AppStream query I was writing today, it would have been useful to have support for the XPath `and` operator. Is that likely to be added?

The query was:
```
custom/value[@key='SomeKey' and text()='true']
```

**Comment by hughsie** [comment]
It could be; have you got a link to the spec with some examples? I presume 'or' is required too?

**Comment by pwithnall** [comment]
https://www.w3schools.com/xml/xpath_operators.asp

**Comment by pwithnall** [comment]
And the spec: https://www.w3.org/TR/xpath-31/#id-logical-expressions

**Comment by hughsie** [comment]
Fixed in https://github.com/hughsie/libxmlb/pull/31 -- be careful about the need for brackets.

**Comment by pwithnall** [comment]
:beers:
