### ISSUE TITLE
XbSilo xb_builder_node_unlink: assertion 'XB_IS_BUILDER_NODE (self)' failed

### ISSUE THREAD

**Issue by bigon** [hughsie/libxmlb#50]
Hello,

On debian unstable (libxmlb  0.1.15) I get the following GLIB critical coming from libxmlb:

> xb_builder_node_unlink: assertion 'XB_IS_BUILDER_NODE (self)' failed

This can be easily reproduce with the following commands:

```shell
$ appstreamcli convert /var/lib/app-info/yaml/ftp.be.debian.org_debian_dists_sid_main_dep11_Components-amd64.yml.gz /tmp/Components-amd64.xml
$ /usr/lib/x86_64-linux-gnu/xb-tool compile /tmp/Components-amd64.xmlb /tmp/Components-amd64.xml
(xb-tool:1900889): XbSilo-CRITICAL **: 19:03:14.826: xb_builder_node_unlink: assertion 'XB_IS_BUILDER_NODE (self)' failed
[...]
```
If somebody want to test and is not running a debian the yaml file can be downloaded at: http://ftp.debian.org/debian/dists/sid/main/dep11/Components-amd64.yml.gz

The [original bug](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/908) has been opened on the gnome-shell project, but the problem seems to be in libxmlb in the end.

**Comment by hughsie** [comment]
@bigon I can't reproduce, but I think it might be something to do with your locale. What are the values of the following environment variables please? `LANGUAGE, LC_ALL, LC_MESSAGES` and `LANG`

**Comment by ximion** [comment]
I can reproduce this issue with
```
LANGUAGE="de"
LANG="de_DE.UTF-8"
``` 
(other values undefined)

**Comment by hughsie** [comment]
> LANGUAGE="de"

Me too! Debugging now!

**Comment by hughsie** [comment]
@ximion -- the XML is invalid:

      <p>
      Zathura can be extended to support multiple document formats using
      plugins. Other features include:
      <ul><li>SyncTeX forward and backward synchronization support.</li><li xml:lang="sv">Stöd för SyncTeX-framåt- och
-bakåtsynkronisering.</li><li xml:lang="ru">SyncTeX поддержка прямой и обратной синхронизации.</li><li xml:lang="nl">SyncTeX vooruit- en achteruitsynchronisatie.</li><li xml:lang="it">Supporto SyncTeX per la sincronizzazione in avanti e all'indietro.</li><li xml:lang="de">Unterstützung für SyncTeX-Synchronisation.</li><li xml:lang="cs">Podpora pro dopředné a zpětné seřízení SyncTeX.</li><li xml:lang="ar">SyncTeX ﺪﻌﻣ ﺎﻠﻣﺯﺎﻤﻧﺓ ﺍﻸﻣﺎﻤﻳﺓ ﻭﺎﻠﺨﻠﻔﻳﺓ.</li><li>Quickmarks and bookmarks.</li><li xml:lang="sv">Snabbmärken och bokmärken.</li><li xml:lang="ru">Быстрые заметки и закладки.</li><li xml:lang="nl">Verwijzingen en bladwijzers.</li><li xml:lang="it">Quickmark e bookmark.</li><li xml:lang="de">Markierungen und Lesezeichen.</li><li xml:lang="cs">Rychlé značky a záložky.</li><li xml:lang="ar">ﺱﺮﻋﺓ ﺎﻠﻋﻼﻣﺎﺗ ﻭﺍﻺﺷﺍﺭﺎﺗ ﺎﻠﻣﺮﺠﻌﻳﺓ.</li><li>Automatic document reloading.</li><li xml:lang="sv">Läs automatisk om dokument.</li><li xml:lang="ru">Автоматическая перезагрузка документов.</li><li xml:lang="nl">Automatische documentherlading.</li><li xml:lang="it">Ricarica automatica del documento.</li><li xml:lang="de">Automatisches Neuladen von Dokumenten.</li><li xml:lang="cs">Automatické znovunahrání dokumentu.</li><li xml:lang="ar">ﺈﻋﺍﺩﺓ ﺖﺤﻤﻴﻟ ﺎﻠﻤﺴﺘﻧﺩﺎﺗ ﺖﻠﻗﺎﺌﻳًﺍ.</li></ul>
    </p>

**Comment by ximion** [comment]
The XML is valid, but it's not valid AppStream - definitely my bug, especially since libappstream actually knows that this is wrong and lets it pass through anyway: https://appstream.debian.org/sid/main/issues/zathura.html
This component should either be rejected, or the description text be sanitized.
I'll have a look, thanks for debugging this!

**Comment by hughsie** [comment]
> thanks for debugging this

I'm just finding the root issue in libxmlb too.

**Comment by ximion** [comment]
I also addressed this in AppStream now (not entirely happy with the fix yet, so I'll probably put in more time later and rework that code a bit).

**Comment by hughsie** [comment]
> I also addressed this in AppStream now.

Many thanks dude. Teamwork! :)

**Comment by pwithnall** [comment]
This change introduced a crash in the unit tests. Fixed in https://github.com/hughsie/libxmlb/pull/58.
