### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by ArchangeGabriel** [hughsie/libxmlb#6]
Hi,

I’m trying to build libxmlb in order to update fwupd to 1.2.0, but I have a failure in tests: https://paste.xinu.at/oWV40/

Any hint?

**Comment by hughsie** [comment]
Is shared-mime-info installed? If not, should we somehow detect that in meson.build?

**Comment by ArchangeGabriel** [comment]
No it was not. That did the trick. I’ve added it as a checkdepends on my PKGBUILD, I don’t know if there is such a thing in meson.
