### ISSUE TITLE
fwupd conflict with `gwyddion` package

### ISSUE THREAD

**Issue by superm1** [hughsie/libxmlb#69]
A downstream bug report in Ubuntu indicated that silos were failing to compile.  After debugging the issue it came down to the user installing the `gwyddion` package.

```
fwupd[920251]: 11:13:34:0743 FuQuirks failed to build silo: failed to compile /usr/share/fwupd/quirks.d/tpm.quirk:ctime=1601481168.750206: cannot process content type application/x-stmprg-spm
```

This package, `gwyddion` installs a mime type specifically:
```
<!-- From module stmprg.c -->
<mime-type type="application/x-stmprg-spm">
  <comment>Omicron STMPRG data parameters</comment>
  <magic priority="80">
    <match type="string" offset="0" value="MPAR"/>
  </magic>
  <glob pattern="tp*"/>
  <glob pattern="TP*"/>
</mime-type>
```
This code comes from:
https://sourceforge.net/p/gwyddion/code/HEAD/tree/trunk/gwyddion/modules/file/stmprg.c

**Comment by superm1** [comment]
I suppose this might actually be improved by https://github.com/hughsie/libxmlb/commit/3101baad938d63f26cda7e3296875adcde282f60 in 0.2.1 though.  The [reporter](https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1899036) used libxmlb 0.1.15

**Comment by hughsie** [comment]
I don't think 3101baa is going to help. The gwyddion package is broken; it claims any files **starting with** `tp` as its own. I think the author probably wanted `*.tp` i.e. an extension instead.
